package Arrays;

public enum GameEnum {
    KING, BORING, FRIEND, LIFE, CAR, SYSTEM, SMARTPHONE, TABLET, LAPTOP, DESKTOP, DOCTOR, ENERGY, HELL, REDBULL, GOAT, HOLLAND, NORWAY, DOCTORATE, PHD, SUMMARIZATION, VALIDATION, 
    SCHOOL, UNIVERSITY, SCIENCE, CHEMICAL, COMPUTER, NESQUICK
    
    
}
